"""Initial migration

Revision ID: f9487e6f01e6
Revises: 
Create Date: 2025-04-23 20:46:11.124662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9487e6f01e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stunt_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('issue_desc', sa.Text(), nullable=True),
    sa.Column('flyer_view', sa.Text(), nullable=True),
    sa.Column('base_view', sa.Text(), nullable=True),
    sa.Column('video_1', sa.String(length=200), nullable=True),
    sa.Column('video_2', sa.String(length=200), nullable=True),
    sa.Column('video_3', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stunt_submission')
    op.drop_table('user')
    # ### end Alembic commands ###
